name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: beksultan
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mydb
        options: >-
          --health-cmd "pg_isready -U beksultan"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports: ["6379:6379"]

    steps:
      - name: 🔄 Репоны жүктеу
        uses: actions/checkout@v3

      - name: 🐍 Python орнату
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Тәуелділіктерді орнату
        run: |
          pip install -r note_api/requirements.txt
          pip install pytest

      - name: 🧪 Тесттерді іске қосу
        env:
          DATABASE_URL: postgresql+asyncpg://beksultan:admin@localhost/mydb
          SECRET_KEY: supersecret
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
        run: |
          pytest note_api/tests/

      - name: 🐳 Docker образын жасау
        run: |
          docker build -t myapp:latest note_api/
